export const data = [
  {
    id: 1,
    title: 'Evangelion',
    info: {
      characters: [
        {
          id: 1,
          name: 'Shinji Ikari',
          age: ['14'],
          height: '1,55 m (5 ′ 1 ″)',
          weight: '58,5 kg (129 lb)',
          birthday: 'June 6th',
          hairColor: 'Brown',
          eyeColor: 'Brown',
          animeDebut: 'Episode 1: Angel Attack',
          image: 'https://tinyurl.com/kkzk49v6',
        },
        {
          id: 2,
          name: 'Rei Ayanami',
          age: ['14'],
          height: '1,54 m (5 ′ 1 ″)',
          weight: '56,2 kg (124 lb)',
          birthday: 'Unknown',
          hairColor: 'Blue light',
          eyeColor: 'Red',
          animeDebut: 'Episode 1: Angel Attack',
          image: 'https://tinyurl.com/4w6j3fk2',
        },
        {
          id: 3,
          name: 'Asuka Langley Soryu',
          age: ['14'],
          height: ' 1,57 m (5 ′ 2 ″)',
          weight: '46 kg (101 lb)',
          birthday: 'December 4th',
          hairColor: 'Orange',
          eyeColor: 'Blue',
          animeDebut: 'Episode 8: Asuka Strikes!',
          image: 'https://tinyurl.com/jnxabzxr',
        },
        {
          id: 4,
          name: 'Misato Katsuragi',
          age: ['30', '43 (3.0)'],
          height: '1,63 m (5 ′ 4 ″)',
          weight: '65.8 kg (145 lb)',
          birthday: 'December 8th',
          hairColor: 'Dark Purple',
          eyeColor: 'Brown',
          animeDebut: 'Episode 1: Angel Attack',
          image: 'https://tinyurl.com/2fm3bdax',
        },
        {
          id: 5,
          name: 'Ryoji Kaji',
          age: ['30'],
          height: '1,78m (5 ′ 10 ″)',
          weight: '72,6 kg (160 lbs)',
          birthday: 'June 17th',
          hairColor: 'Brown',
          eyeColor: 'Green',
          animeDebut: 'Episode 8: Asuka Strikes!',
          image: 'https://tinyurl.com/bsnjnher',
        },
        {
          id: 6,
          name: 'Gendo Ikari',
          age: ['48 (anime)', '62 (3.0)'],
          height: '1,92m',
          weight: 'Unknown',
          birthday: 'April 28th',
          hairColor: 'Brown',
          eyeColor: 'Brown',
          animeDebut: 'Episode 1: Angel Attack',
          image: 'https://tinyurl.com/h8dmxayf',
        },
        {
          id: 7,
          name: 'Kaworu Nagis',
          age: ['Unknown'],
        },
        {
          id: 8,
          name: 'Mari Makinam,llustrious',
          age: ['16 (Manga)', '45 approximately (3.0)'],
          image: 'https://tinyurl.com/yc5zv7ej',
        },
        {
          id: 9,
          name: 'Ritsuko Akag',
          age: ['30 (anime)', '44 (3.0)'],
          image: 'https://tinyurl.com/tuf6b5w',
        },
        {
          id: 10,
          name: 'Yui Ik',
          age: ['27 (at the time of his death)'],
          height: '1,54 m (5 ′ 1 ″)',
          animeDebut: 'Episode 16: Splitting of the Breast',
          image: 'https://tinyurl.com/sbn9uww9',
        },
        {
          id: 11,
          name: 'Kozo Fuyutsu',
          age: ['58 (anime)', '72 (3.0)'],
          image: 'https://tinyurl.com/58djem8a',
        },
        {
          id: 12,
          name: 'Toji Suzuhar',
          age: ['14'],
          image: 'https://tinyurl.com/2amt9h7s',
        },
        {
          id: 13,
          name: 'Pen Pen',
          age: ['Unknown'],
          image: 'https://tinyurl.com/3jwrybp5',
        },
        {
          id: 14,
          name: 'Maya Ibuki',
          age: ['14'],
        },
        {
          id: 15,
          name: 'Makoto Hyuga',
          age: ['21 (approximately)'],
        },
        {
          id: 16,
          name: 'Shigeru Aoba',
          age: ['Unknown'],
        },
        {
          id: 17,
          name: 'Hikari Horak',
          age: ['14'],
        },
        {
          id: 18,
          name: 'Kensuke Aida',
          age: '[14]',
        },
        {
          id: 19,
          name: 'Keel Lorentz',
          age: ['67 (approximately)'],
        },
      ],
      curiosities: [
        'Las cejas de Ritsuko Akagi son de distinto color porque su color de pelo natural es rojo y se tiñe de rubio.',
        'El Segundo Impacto ocurrió el 13 de Septiembre del año 2000. También es el día de nacimiento de Kaworu Nagisa.',
        'En el episodio 2 se ve por primera vez el SDAT de Shinji. Es un reproductor de música digital en cinta magnética tipo cassette. Las pistas que escucha Shinji van del 25 al 26 y viceversa, lo que puede ser una referencia al final de la serie, transcurrido en los episodios 25 y 26.',
        "La cerveza que ingiere Misato Katsuragi en los primeros capítulos es una marca de cerveza 'real'. Esta marca es conocida como 'YEBISU'. La firma de dicha cerveza se quejó a Gainax y por eso en los capítulos posteriores al 5, Misato cambia de marca de cerveza.",
        'Los nombres de casi todos los personajes son de barcos (o tipos de barcos) de guerra japoneses: Akagi, Aoba, Ayanami, Fuyutsuki, Hyuga, Katsuragi, Soryu, Langley (estadounidense). También muchos nombres están basados en términos náuticos: Ikari/ancla; Kaji/remo corto o timón; Rokubungi/sextante (instrumento para medir ángulos); Kiel (keel)/quilla.',
        'Los nombres de Hikari Horaki y sus hermanas (Kodama y Nozomi) son los tres servicios del Shinkansen (tren bala).',
        "Cuando Asuka se muda con Shinji antes de la pelea sincronizada, cierra una puerta corrediza y dice que 'es el muro indestructible de Jericó'. Esta es una escena de la película It Happened One Night.",
        "En el episodio 9 el EVA-02 destruye un edificio que tenía un cartel que decía 'Studio Fantasia'. Este era el estudio de animación que trabajó con Gainax en la realización de Otaku no Video.",
        'El episodio 13 es una copia casi textual de varias escenas de la película The Andromeda Strain, basada en la novela de Michael Crichton, que cuenta sobre la diseminación de un organismo microscópico extraterrestre y los intentos de las agencias de inteligencia de EE.UU. para contenerlo.',
        'En el episodio 18 se puede oir que el personal de Estados Unidos realmente habla en inglés, siendo un detalle que se agradece.',
        'El subtítulo Do You Love Me? del episodio 25 es el título de un libro escrito por Ronald David Laing. Es una colección de poemas escritos por este psiquiatra, que giran en torno al tema de la necesidad de amor en la sociedad.',
        'Los monolitos de SEELE están inspirados en los monolitos que aparecen en la película 2001: Odisea del espacio, y simbolizan la evolución.',
        'El ending Fly Me to the Moon fue originalmente uno de los grandes éxitos de Frank Sinatra.',
      ],
    },
  },
  {
    id: 2,
    title: 'Demon Slayer (Kimetsu no Yaiba)',
    info: {
      characters: [
        {
          id: 1,
          name: 'Tanjiro Kamado',
          age: [
            '13 (Chapter 1)',
            '15 (End of Chapter 5)',
            '16-17 (End of Chapter 204)',
          ],
          height: '165 cm',
          weight: '61 kg (134 lb)',
          birthday: 'July 14th',
          hairColor: 'Black to Red',
          eyeColor: 'Dark Red',
          animeDebut: 'Episode 1',
          image: 'https://tinyurl.com/2p949u6x',
        },
        {
          id: 2,
          name: 'Nezuko Kamado',
          age: ['12 (Physically)', '14 (Chronologically)'],
          height: '153 cm',
          weight: '45 kg (99 lb)',
          birthday: 'December 28th',
          'hair Color': ['Black (Human)', 'Black to Flame orange (Demon)'],
          eyeColor: ['Pale Pink (Demon)', 'Dark Pink (Human)'],
          animeDebut: 'Episode 1',
          image: 'https://rb.gy/sygcws',
        },
        {
          id: 3,
          name: 'Tanjuro Kamado',
          hairColor: 'Black to Red',
          eyeColor: 'Dark Red',
          animeDebut: [
            'Episode 1 (Partial Appearance)',
            'Episode 19 (Full Appearance)',
          ],
          image: 'https://rb.gy/zxv5db',
        },
        {
          id: 3,
          name: 'Tomioka Giyu',
          age: ['19 (Chapter 1)', ' 21 (As of Chapter 28)'],
          height: '176 cm',
          weight: '69 kg (152 lb)',
          birthday: 'February 8th',
          'hair Color': 'Black',
          eyeColor: 'Dark Blue',
          animeDebut: 'Episode 1',
          image: 'https://rb.gy/52rchv',
        },
        {
          id: 4,
          name: 'Rengoku Kyojuro',
          age: ['20'],
          height: '177 cm',
          weight: '72 kg (159 lb)',
          birthday: 'May 10th',
          hairColor: 'Gold with Red Tips',
          eyeColor: 'Gold with Red Irises',
          animeDebut: 'Episode 21',
          image: 'https://rb.gy/ayrkov',
        },
      ],
      seasonOne: {
        episodes: [
          {
            castellano: {
              '01': {
                title: 'Crueldad',
                release: '6 de abril de 2019',
              },
              '02': {
                title: 'El instructor, Sakonji Urokodaki',
                release: '13 de abril de 2019',
              },
              '03': {
                title: 'Sabito y Makomo',
                release: '20 de abril de 2019',
              },
              '04': {
                title: 'Selección final',
                release: '27 de abril de 2019',
              },
              '05': {
                title: 'Tu acero',
                release: '4 de mayo de 2019',
              },
            },
          },
          {
            japones: {
              '01': {
                title: 'Zankoku',
                release: '6 de abril de 2019',
              },
              '02': {
                title: 'Iku-shu Urokodaki Sakonji',
                release: '13 de abril de 2019',
              },
              '03': {
                title: 'Sabito to Makomo',
                release: '20 de abril de 2019',
              },
            },
          },
        ],
      },
    },
  },
]
